/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenum;

/**
 *
 * @author adminlinux
 */
public enum EnumCompraEntreRegimenes {
    GRANDECONTRIBUYENTECOMPRAAGRANDECONTRIBUYENTE,
    GRANDECONTRIBUYENTECOMPRAARGIMENCOMUN,
    GRANDECONTRIBUYENTECOMPRAARGIMENSIMPLIFICADO,
    REGIMENCOMUNCOMPRAAGRANDECONTRIBUYENTE,
    REGIMENCOMUNCOMPRAAREGIMENCOMUN,
    REGIMENCOMUNCOMPRAAREGIMENSIMPLIFICADO,
    REGIMENSIMPLICOMPRAAGRANDECONTRIBUYENTE,
    REGIMENSIMPLICOMPRAAREGIMENCOMUN,
    REGIMENSIMPLICOMPRAAREGIMENSIMPLIFICADO
}
