/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isoftconta.servicios;

/**
 *
 * @author adminlinux
 */
public  enum EnumDocumentoSoporte {
    FACTURACOMPRA0,
    FACTURAVENTA1,
    RECIBOCAJAMENOR2,
    COMPROBANTEINGRESO3,
    COMPROBANTEEGRESO4,
    COMPROBANTEAJUSTE5,
    NOTACONTABILIDAD6,
    CIERREFINMES7,
    CIERREFINANO8,
    NOTADEBITO9,
    NOTACREDITO10,
    COMPROBANTECONSIGNACION11,
    TRANSACCIONCAJEROELECTRONICO12,
    CONCILIACIONBANCARIA13,
    COMPROBANTECAUSACIONEGRESO14,
    COMPROBANTECAUSACIONINGRESO15,
    CARGUEINICIALSALDOS16,
    COMPROBANTECAUSACIONNOMINA17,
    NOVEDADNOMINA18,
    SALDOINICIAL19,
    NOTIFICACIONDEVOLUCIONVENTA20
  
    
}
